name: CD Workflow

on:
  workflow_run:
    workflows:
      - "CI Workflow" # CI 워크플로우의 이름을 참조
    types:
      - completed

env:
  ECR_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}
  PROFILE: "dev"
  SERVICE: "default"

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      profile: ${{ steps.set-env.outputs.profile }}
      service: ${{ steps.set-service.outputs.service }}
    steps:
      - name: Set dynamic PROFILE based on branch
        id: set-env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "PROFILE=prod" >> $GITHUB_ENV
            echo "profile=prod" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "PROFILE=dev" >> $GITHUB_ENV
            echo "profile=dev" >> $GITHUB_ENV
          fi

      - name: Set SERVICE variables
        id: set-service
        run: |
          echo "SERVICE=$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_ENV
          echo "service=${SERVICE}" >> $GITHUB_ENV

  build:
    if: ${{ github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest
    needs: setup-env
    steps:
      # 1. GitHub 저장소 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

        # 2. Java 버전 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3. Gradle 빌드 및 Docker 이미지 생성
      - name: Build Docker image
        run: |
          # Gradle 빌드 명령어 실행
          ./gradlew build
          # Docker 이미지 빌드
          docker build -t ${SERVICE}:${PROFILE}-latest .
      # 4. AWS 자격증명
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # 5. DockerHub / ECR 로그인
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # 6. Docker 이미지 ECR에 푸시
      - name: Push Docker image to ECR
        run: |
          docker tag ${SERVICE}:${PROFILE}-latest ${ECR_URI}:${PROFILE}-latest
          docker push ${ECR_URI}:${PROFILE}-latest
  deploy:
    runs-on: ubuntu-latest
    needs:
      - setup-env
      - build
    env:
      PROFILE: ${{ needs.setup-env.outputs.profile }}
      SERVICE: ${{ needs.setup-env.outputs.service }}
    steps:
      # EC2 인스턴스에 SSH로 접속하여 Docker 이미지 풀 및 실행
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # AWS CLI로 ECR 로그인
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            
            # 기존 컨테이너가 있다면 종료하고 삭제
            docker stop ${{ env.SERVICE }}-${{ env.PROFILE }} || true
            docker rm ${{ env.SERVICE }}-${{ env.PROFILE }} || true
            # 브랜치에 따른 포트 설정
            if [[ ${{ env.PROFILE }} == "prod" ]]; then
              PORT=8080
            elif [[ ${{ env.PROFILE }} == "dev" ]]; then
              PORT=8081
            else
              PORT=8080
            fi

            echo "Deploying ${{ env.SERVICE }} to port ${PORT} with profile ${{ env.PROFILE }}"
            echo "Deploying $SERVICE to port ${PORT} with profile $PROFILE"
            echo "Deploying ${{SERVICE}} to port ${PORT} with profile ${{PROFILE}}"
            
            # ECR에서 Docker 이미지 풀
            docker pull ${{ env.ECR_URI }}:${{ env.PROFILE }}-latest

            # Docker 컨테이너 실행
            docker run -d \
            --name ${{ env.SERVICE }}-${{ env.PROFILE }} \
            -p ${PORT}:${PORT} \
            -e SPRING_PROFILES_ACTIVE=${{ env.PROFILE }} \
            ${{ env.ECR_URI }}:${{ env.PROFILE }}-latest
