name: Notify Discord Workflow

on:
  workflow_call:
  	inputs:
	  branch-type:
		  description: "main or dev"
		  required: true
		  type: string
	  build-result:
		  description: "success or failure"
		  required: true
		  type: string

jobs:
  notify-discord:
  	runs-on: ubuntu-latest
	steps:
	- name: Notify Discord
	  uses: tsickert/discord-webhook@v6.0.0
	  with:
		  webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
		  content: ":loudspeaker: ${{inputs.branch-type}} branch's build result is ${{ inputs.build-result }}."
